### ISSUE TITLE
Dockerfile / zbrowse.sh mismatch

### ISSUE THREAD

**Issue by jsmonet** [zmap/zbrowse#4]
super simple, using the Dockerfile with this I get:
Error: Cannot find module '/zbrowse/js/index.js'
as part of the error message when I run the docker build then docker run steps. 

My env: osx high sierra
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

The Dockerfile copies the contents of js/ into /zbrowse, but not as the js dir. You need to specify
COPY js /zbrowse/js

Just doing that now causes the npm install step to fail. I abused WORKDIR for that because I'm lazy. Full version of the dockerfile I've used successfully:

```
FROM ubuntu
RUN apt-get update && apt-get install -y \
  npm \
  nodejs \
  chromium-browser \
&& rm -rf /var/lib/apt-lists/*

COPY js /zbrowse/js
COPY zbrowse.sh /zbrowse

WORKDIR /zbrowse/js
RUN npm install

WORKDIR /zbrowse

RUN chmod +x zbrowse.sh

ENTRYPOINT ["/zbrowse/zbrowse.sh"]```

**Comment by kumarde** [comment]
Thank you!

**Comment by kumarde** [comment]
Fixed by https://github.com/zmap/zbrowse/pull/5. 

Thank you for your contribution!
